### ISSUE TITLE
Lindbergh Models Documentation

### ISSUE THREAD

**Issue by ghost** [JayFoxRox/Lindbergh-Emulator#6]
Very few lines of documentation are written around the web about the different models of Lindbergh. It should be a good thing to document (text and photos) all of the parts/specs about each model.

* Lindbergh Yellow
* Lindbergh Red
* Lindbergh RedEx
* Lindbergh Silver (Satellite Terminal)
* Lindbergh Blue

Moreover it is necessary to decide if this emulator should support Lindbergh Blue games, since it has a Windows Embedded OS instead Montavista Linux.

**Comment by JayFoxRox** [comment]
This is not an issue of the emulator.

Eitherway: 
* SegaRetro is the usual source for good info: http://segaretro.org/Sega_Lindbergh has some good information.
* system 16 also has some info about Lindbergh: http://www.system16.com/museum.php?id=1 .

Note that other hardware will also work as replacement. So these specs are not set in stone.

---

Blue games can easily be patched to work on Windows. There are only 2 games too (and some variations of each).
This "emulator" is actually more of a wrapper / Linux compatibility layer, rather than an LLE.
As such, it can not emulate Lindbergh Blue. I think a fork or clean seperation of code might be useful to re-use code parts which might be similar in Blue.

---


We should mirror game manuals and open source documents instead. Because while those are still around, they will become harder to find soon. We also have to find a way to properly dump and preserve games. But: This is also not an emu project, and should be contributed to redump or similar projects.

There are also known exploits to run custom code on Lindbergh (which can be used for research and development). That also has to be documented or such valuable information will be lost.
However, that should also be a seperate project.

**Comment by ghost** [comment]
> This is not an issue of the emulator.

Yeah, I was trying to put the focus on the fact we've to preserve all the material we can find.
> Note that other hardware will also work as replacement. So these specs are not set in stone.

Of course, I saw people customizing their Lindy adding more memory / replacing the stock P4 with a slightly more powerful version

> We should mirror game manuals and open source documents instead

I've already archived all the manuals I've been able to get around the net, since I'd like to contribute with the project but I've very limited basis about reverse engineering and emulation, and that's the only useful thing I can do.
However, I don't know if the upload of such material is permitted (or not) here for legal stuff (or maybe you want to save it in another place).

**Comment by JayFoxRox** [comment]
I'd like to avoid such copyrighted material on this repo. Try to get it on archive.org or keep good backups which you might be able to privately share later.

**Comment by ScapeGoat43** [comment]
so how many manuals did you find for lindbergh?

**Comment by ghost** [comment]
I was able to count 26 available manuals on the net at the moment (counting cabinet variants, e.g. Standard and Deluxe and System manuals). 
You can get the most part of them directly from Sega @ http://www.segaarcade.com/manuals.
We obviously cannot copy them here due to copyright issues.

**Comment by ScapeGoat43** [comment]
well do you need any other manuals or any missing manuals?

**Comment by ghost** [comment]
Well, I wasn't able to locate the pdf for japan exclusive games (e.g. Initial D 5), but I don't need them right now. Thanks for your interest ;-)

**Comment by ScapeGoat43** [comment]
so how is the progress?

**Comment by ghost** [comment]
I suppose it's all steady at the moment, no people are working on it, since Jay has to follow other projects and I don't have time due to university (exams and master thesis). A bit ago Jay released some tools in order to help the development of this wrapper (https://github.com/JayFoxRox/lindbergh-tools).
I hope I can start working again on this project, but it won't be in the near future :-/
